### ISSUE TITLE
Chrome拡張に表示するアイコン作成

### ISSUE THREAD

**Issue by nyakome** [oasi-z/taro#4]

**Comment by radiocat** [comment]
@nyakome アイコンはダミーでお願いします

**Comment by nyakome** [comment]
アイコン(ダミー)を表示するようにしました。
拡張を有効にするとブラウザにアイコンが表示されます。

**Comment by radiocat** [comment]
現状、extensionのルートは `/src` の想定なのでアイコン設定の書いてある `manifest.json` は `/src`の下に配置してほしい。そうしないとREADMEまでがextensionのソースに含まれるので。

**Comment by radiocat** [comment]
ごめん、色々sampleを漁ってみたらREADMEが含まれるのは普通みたい。逆に `/src`が要らない気がしてきた。↓こんな感じのほうがいいんじゃないかな？

```
├ css
├ icons
├ js
├ lib
│
├ manifest.json
├ popup.html
├ options.html
├ README.md
```

このへん参考
https://github.com/GoogleChrome/chrome-app-samples
https://github.com/orbitbot/chrome-extensions-examples

**Comment by nyakome** [comment]
問題ないです。
http://liginc.co.jp/web/tool/browser/163575
↑を見てもルートの下にimgやjsフォルダを置いているようですね。

こちらはクローズします。
